apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.nginx.name}}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      server: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        server: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nginx.image.port }}